#!/usr/bin/env bash

if [[ $# > 0 ]]; then
    while read option; do
        case ${option} in
            *) info.error "Unknown option $option"; info.usage; exit 2; ;;
        esac
    done <<< $(for i in "$@"; do echo "$i"; done);
fi

function getRepoApiUrl() {
    git config --get remote.${remote}.url |
    sed 's|^git@github.com:|https://api.github.com/repos/|' |
    sed 's|\.git$||';
}

tag1=`git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1)`
tag2=`git describe --abbrev=0 --tags $(git rev-list --tags --max-count=1)`
desc="## Change Log:\n -\n -\n\n ### [View Commits](https://github.com/alek13/slack/compare/${tag1}...${tag2})"

apiUrl="`getRepoApiUrl`/releases";
json='{
    "tag_name": "%s",
    "draft": true,
    "body": "%s"
}';
json=`printf "${json}" "${tag2}" "${desc}"`


c.header ' Create release on GitHub: ';
echo "${json}"
curl \
    -X POST \
    -H "Authorization: token $token" \
    -H "Accept: application/vnd.github.v3+json" \
    --data "${json}" \
    ${apiUrl}
